variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375
  PKG_PATH: github.com/jetstack/vault-unsealer
  GORELEASER_HASH: f7dbad6cc4f8424eceb7a2d74dc21472f4ebde6041abf12ff1b44d766c8ad836
  GORELEASER_VERSION: 0.98.0

stages:
- build
- deploy
- docker

# configure $GOPATH correctly on all build stages
before_script:
  - unset GPG_PRIVATE_KEY GITHUB_TOKEN DOCKER_AUTH_CONFIG
  - mkdir -p "${GOPATH}/src/${PKG_PATH}" && rmdir "${GOPATH}/src/${PKG_PATH}"
  - mv "${CI_PROJECT_DIR}" "${GOPATH}/src/${PKG_PATH}"
  - cd "${GOPATH}/src/${PKG_PATH}"
  - mkdir -p "${CI_PROJECT_DIR}"

after_script:
  - cd "/"
  - rm -rf "${CI_PROJECT_DIR}"
  - mv "${GOPATH}/src/${PKG_PATH}" "${CI_PROJECT_DIR}"

verify:golang:
  image: golang:1.11.4
  stage: build
  tags:
  - docker
  script:
  - make verify

build:golang:
  image: golang:1.11.4
  stage: build
  tags:
  - docker
  script:
  - make build
  except:
  - tags
  artifacts:
    paths:
    - vault-unsealer_linux_amd64

deploy:release:
  image: golang:1.11.4
  stage: deploy
  tags:
  - docker
  before_script:
  - echo "${GPG_PRIVATE_KEY}" | gpg --import -
  - unset GPG_PRIVATE_KEY DOCKER_AUTH_CONFIG
  - curl --fail -sL https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz > /tmp/goreleaser.tar.gz
  - echo "${GORELEASER_HASH}  /tmp/goreleaser.tar.gz" | sha256sum -c
  - cd /usr/local/bin && tar xvfz /tmp/goreleaser.tar.gz goreleaser
  - mkdir -p "${GOPATH}/src/${PKG_PATH}" && rmdir "${GOPATH}/src/${PKG_PATH}"
  - mv "${CI_PROJECT_DIR}" "${GOPATH}/src/${PKG_PATH}"
  - cd "${GOPATH}/src/${PKG_PATH}"
  - mkdir -p "${CI_PROJECT_DIR}"
  script:
  - goreleaser
  - mv "dist/linux_amd64/vault-unsealer" vault-unsealer_linux_amd64
  only:
  - tags
  artifacts:
    paths:
    - vault-unsealer_linux_amd64

docker:master_build_push:
  before_script: []
  after_script: []
  image: docker:1.12
  stage: docker
  tags:
  - docker
  services:
  - docker:dind
  script:
  - apk --update add make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_push IMAGE_TAGS="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID} canary"
  only:
  - master

docker:tags_build_push:
  before_script: []
  after_script: []
  image: docker:1.12
  stage: docker
  tags:
  - docker
  services:
  - docker:dind
  script:
  - apk --update add make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_push IMAGE_TAGS="${CI_COMMIT_TAG} latest"
  only:
  - tags
