builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
archive:
  format: binary
release:
  github:
    owner: jetstack
    name: vault-unsealer

sign:
  artifacts: checksum
  signature: "${artifact}.asc"
  args: ["-u", "tech+releases@jetstack.io", "--armor", "--output", "${signature}", "--detach-sign", "${artifact}"]
